pool:
  vmImage: ubuntu-latest

steps:
- script: |
      git fetch --unshallow
  displayName: 'convert to non-shallow clone' 
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'victoredu22'
    projectKey: 'victoredu22_clinica'
    projectName: 'clinica'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonar'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false